### PR TITLE
upgraded next to 12.3 and tailwind to 4.0

### PR DESCRIPTION
**Pull request by iam-vipin**
i upgraded the next and tailwind to latest version i found check it out

### CODE REVIEW

**Comment by iam-vipin** [comment]
i cant fix this help me

**Comment by iam-vipin** [comment]
although i upgraded next and tailwind 
check filechanged

**Comment by ridhof** [comment]
have you tried to run `npm i` and `next build` in your dev environment?

**Comment by naufaldi** [comment]
@itsvipindev updated a wrong dependencies, its `tailwindcss` not `tailwind` . Its different

**Pull request closed without merging**
