### PR TITLE
added some animation on page

### LINKED ISSUE #5: Add Animation to Landingpage
Add animation to Landingpage. You can use
- Framermotion
- AOS
- GSAP

Example:
- [x] #11
- [x] #12

### LINKED ISSUE #11: animation when hover

### PR DESCRIPTION
**Pull request by Shivam164**
I have added zoom-in on hover animation at two places, one at choosing your plan and another at features. I thought too many animations will look weird on the site that's why I didn't add too many.

### CODE REVIEW

**Comment by Shivam164** [comment]
@naufaldi Due to some reason my pull request is failing vercel check. Can you tell me why this is happening?

**Comment by naufaldi** [comment]
the problem is on vercel nodejs, already update nodejs. Can you provide screenshot / video when hover? can you add incoming animation too? 

example see this website
[Logos Festival](https://logos-fest.vercel.app/)

**Comment by Shivam164** [comment]
> the problem is on vercel nodejs, already update nodejs. Can you provide screenshot / video when hover? can you add incoming animation too?
> 
> example see this website [Logos Festival](https://logos-fest.vercel.app/)

**Comment by Shivam164** [comment]
Screenshot (118)
Screenshot (119)
Screenshot (120)

**Comment by Shivam164** [comment]
@naufaldi Here are screenshots.

**Comment by naufaldi** [comment]
Thanks you!

**Comment by Shivam164** [comment]
@naufaldi Hey, can you add Hacktoberfest-accepted tag to this pull request?

**Pull request merged**
