### PR TITLE
fix: Add ESLint and Prettier for standardization

### LINKED ISSUE #17: Add Linter
For better standarization for Linter, we should add ESLINT and Prettier. So, this feature

- Add in script to auto Lint for eslint and prettier
- Use standard linter like airbnb 

Problem, who should repair or improve when code goes wrong because eslint and prettier make code show error?
Maybe will add issues regarding improve code base on linter.

### PR DESCRIPTION
**Pull request by Vinitvh**
- Added ESLint with script `lint:fix:  "eslint . --fix"` which checks for linting problems.
-  Added Prettier with script `format:  "prettier . --write"` which formats code according to config.

closes #17

### CODE REVIEW

**Comment by naufaldi** [comment]
1. Can you provide screenshot if  ESLint and Prettier work with script?
2. Can you use `npm` not `yarn` and not uploaded `yarn.lock` file?

**Comment by Vinitvh** [comment]
This is the screenshot for `ESLint` script.
lint

This is the screenshot for `prettier` script.
prettier

- Both `yarn` and `npm` can be used.

**Comment by naufaldi** [comment]
can you resolve conflict and make file not error when production @Vinitvh ?

**Comment by Vinitvh** [comment]
Hi @naufaldi, looks like I'm having issues solving merge conflicts. Sorry for that. Will try to resolve those as soon as possible.

**Pull request closed without merging**
