### PR TITLE
feat: add Github Action CI to run test on Pull Request #10

### LINKED ISSUE #10: Add CI to Repo
For better development and reproduce error, we need to add CI in this repo

### PR DESCRIPTION
**Pull request by ridhof**
closes #10 

changes:
- add a Github Action CI yaml to run `yarn build` when a new commit is pushed over a Pull Request, example: [https://github.com/ridhof/next-landing-vpn/pull/1](https://github.com/ridhof/next-landing-vpn/pull/1)

some things should be noted:
- we have to be clear, are we going to use `yarn` or `npm`. because currently we have both `package-lock.json` that was generated by `npm`, and `yarn.lock` that was generated by `yarn`.
- after deciding which one we going to use, we have to remove the unused lock file. I think it can be a new different issue for hacktoberfest to delete the lock file
- currently, I am using `yarn` for CI
- when using `npm i`, I couldn't install the packages. Is this expected?
- I got an error when running `yarn next export`, is this expected?

### CODE REVIEW

**Comment by ridhof** [comment]
I'd like you check my comment @naufaldi 
thanks

**Comment by corners2wall** [comment]
@ridhof, Two configuration files for this project are excessive. File package-lock.json was added in [pr](https://github.com/naufaldi/next-landing-vpn/pull/8). I think,  that was mistake.

**Comment by naufaldi** [comment]
@ridhof sorry for late review.
1. We should use `npm` instead of `yarn` 
2. I will create another PR for remove `yarn-lock` 
3. is there are code error when using npm?
4. there should be no problems during the install and build process because vercel itself is also no problem.

So, @ridhof must change `yarn` to `npm` in CI?

**Comment by ridhof** [comment]
I'll change the CI to use `npm` instead of `yarn`

currently, when running `npm i` I got this error message
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: next-landing-vpn@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2 || ^18.0.0-0" from next@12.3.1
npm ERR! node_modules/next
npm ERR!   next@"12.3.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

the workaround I did is by using `npm i --force`

and got no error from `npm run export`

**Comment by ridhof** [comment]
updated, please kindly check @naufaldi

**Comment by naufaldi** [comment]
nice, well done @ridhof !

**Pull request merged**
